import React from 'react'
import { Segment, Divider, Image, List, Header } from 'semantic-ui-react'
import { Link } from 'react-router'
import './Crowdfund.scss'
import icon1 from './crowd/icon1.png'
import icon2 from './crowd/icon2.png'
import icon3 from './crowd/icon3.png'

const CrowdfundInfoView = () => {
  return (
    <div className='ui one column centered grid'>
      <div className='column'>
        <div className='crowdfund-info-banner' />
        <h1 className='ui header inverted'>
          Turn Your Talent Invsetment From The Crowd
        </h1>
        <h3 className='ui header inverted'>
          FanTank's measurement and filtering technology is generated by the collective votes from the crowd that
           functions as the talent scouts with less subjectivity.
        </h3>
        <Segment secondary inverted padded>
          <div className='ui three column centered padded grid'>
            <div className='column'>
              <Image centered src={icon1} />
              <h3>Get Exposed To More Investors Globally</h3>
              <Divider horizontal inverted section />
              <p>Our technologies enable potential investors, distributors, agents, fans, brand managers, and other
                artists to locate you more efficiently</p>
            </div>
            <div className='column'>
              <Image centered src={icon2} />
              <h3>Unleash Your Artistic Vision</h3>
              <Divider horizontal inverted section />
              <p>Keep Creative Control Of Your Art</p>
            </div>
            <div className='column'>
              <Image centered src={icon3} />
              <h3>Team Up With Experts And Innovators</h3>
              <Divider horizontal inverted section />
              <p>We are leaders in converging technology and finance with Arts & Entertainment while bringing financial
                 services and risk hedging strategies to the industry and empowerment to artists</p>
            </div>
            <div className='column'>
              <Link to='/terms'>LEGAL DISCLAIMER</Link>
            </div>
          </div>
        </Segment>

        <Segment tertiary inverted padded>
          <div className='ui centered padded grid'>
            <div className='column'>
              <h2>Get Started</h2>
              <span>Want to raise money via equity crowdfunding?</span>
              <div style={{ marginTop: '1em' }}>
                <Link className='ui button primary inverted' to='/signup'>Sign Up</Link>
              </div>
            </div>
          </div>
        </Segment>

        <Header inverted>FAQ</Header>
        <Segment attached='bottom' tertiary inverted padded>
          <div className='ui padded two column grid'>
            <div className='column'>
              <List relaxed inverted style={{ textAlign: 'left' }}>
                <List.Item>
                  <List.Header>What is equity crowdfunding?</List.Header>
                  <List.Description>
                    With equity crowdfunding, investors get a financial stake in you as a brand and / or a
                    particular project they’re supporting. Unlike crowd pledging, where the funds are basically a gift
                    usually in exchange for perks.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>Why should I consider equity crowdfunding?</List.Header>
                  <List.Description>
                    Equity crowdfunding allows you to offer investors a real stake in your artistic vision.
                    Our platform gives you exposure to a passionate community of art lovers who are looking to invest
                     in the next big star while allowing you to keep artistic control.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>Who can use this service?</List.Header>
                  <List.Description>
                    Artists - current regulations only allow companies that are incorporated in the USA to raise
                    capital. Investors - we are currently only allowing investors located in the USA to invest,
                    but this is subject to extend to other parts of the world over the next 12 months as global
                    equity crowd funding laws evolve.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>How much does it cost the artist?</List.Header>
                  <List.Description>
                    Nothing. Zero. Zip. Nada… Once an artist is selected for equity crowd funding by the collective
                    votes of our users, we then leverage the combination of our network of high net worth individuals,
                    distributors, producers, hedge funds, VC firms, financial services companies, or FanTank to
                    mobilize your project to pay for underwriting, legal, accounting, marketing, and broker dealer
                    fees that can range from $50,000 to $250,000 depending upon how much is raised for your project.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>How does investing work?</List.Header>
                  <List.Description>
                    Investing in an artist or artistic project means you own a piece of that project and are along for
                    the ride, whether up or down. With this partnership, all investment transactions take place
                    on <a href='http://www.bankroll.com'>www.bankroll.com</a>
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>What is the definition of an "Artrepreneur"?</List.Header>
                  <List.Description>
                    An Artrepreneur is anyone whether an artist or evaluator who has a strong passion and interest in
                    the Arts with an intent to monetize that passion.
                  </List.Description>
                </List.Item>
              </List>
            </div>
            <div className='column'>
              <List relaxed inverted style={{ textAlign: 'left' }}>
                <List.Item>
                  <List.Header>What are the different roles between FanTank and Bankroll?</List.Header>
                  <List.Description>
                    FanTank provides the technologies and services that incentive artists to post content and evaluators
                    to give their feedback that ultimately creates a form of measurement on artist content.
                    BankRoll’s main role is to handle any and all aspects of the actual POT (Point of Transaction) where
                     the investment in an artist is done
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>Does the Artist have access to the full amount raised in one payment?</List.Header>
                  <List.Description>
                    No. There are up to 2% brokerage and other processing fees taken out of the amount raised.
                    The rest is distributed to artists and / or paid direct to vendors from a indepedent law
                    and / or accounting firm’s professionally funds administered escrow account. There are also agreed
                    upon deliverable schedules that must be met from artist prior to dispursements.
                    <Link to='/pricing'>View Our Project Offering</Link>
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>How much can I raise?</List.Header>
                  <List.Description>
                    You can raise up to $1,000,000 with a Title III offering, and there is no limit on a 506(c)
                    offering. FanTank and BankRoll allows you to do a Title III offering, a 506(c) offering, or both.
                    FanTank does not do micro deals.  We typically will process funding deals of at least $500,000 in an
                    effort to give your project the best chance for commercial success and to maximize ROI to investors.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>What are the different ways I can raise money?</List.Header>
                  <List.Description>
                    You can decide to offer company shares in exchange for investment with an equity offering, offer a
                    revenue share to investors, or even raise funds via a debt offering.
                  </List.Description>
                </List.Item>
                <List.Item>
                  <List.Header>
                    Is there a difference between applying to raise on the FanTank site or applying on
                    the BankRoll site?
                  </List.Header>
                  <List.Description>
                    Yes. At the current time you can only be listed on BankRoll’s site. Also, the artist cannot “apply".
                    You could be selected based upon the collective votes from the crowd. On our platfrom, the crowd is
                    not only the investor but they are they are the A&R / talent scouts as well. If your selected, a
                    FanTank team member will contact you to send you a formal proposal for listing you on our sites for
                    an equity crowd funding campaign.
                  </List.Description>
                </List.Item>
              </List>
            </div>
          </div>
        </Segment>
      </div>
    </div>
  )
}

export default CrowdfundInfoView
